name: Strong Field Literature Report


on:

  workflow_dispatch:


  schedule:

    # 每周一法国时间08:00
    # UTC 06:00
    #- cron: "0 6 * * 1"

    - cron: "*/10 * * * *"


jobs:


  report:


    runs-on: ubuntu-latest

    timeout-minutes: 15
    
    steps:


    - uses: actions/checkout@v4


    - uses: actions/setup-python@v5

      with:

        python-version: "3.11"



    - name: Install dependencies

      run: |

        sudo apt-get update

        sudo apt-get install -y fonts-noto-cjk

        pip install -r requirements.txt



    - name: Run literature agent

      env:

        SMTP_PASSWORD:
          ${{ secrets.SMTP_PASSWORD }}

        DEEPSEEK_API_KEY:
          ${{ secrets.DEEPSEEK_API_KEY }}


      run:

        python main.py
